import { League_Spartan } from 'next/font/google';
import { ReduxProvider } from './redux/provider';
import Navbar from './components/Navbar';

import './globals.css';
const spartan = League_Spartan({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<ReduxProvider>
			<html lang="en" className="bg-background-dark2">
				<body className={spartan.className}>
					<Navbar />
					{children}
				</body>
			</html>
		</ReduxProvider>
	);
}
